"""auto-vote

Revision ID: fc1ca16e36f7
Revises: a93ea77efd2c
Create Date: 2022-10-13 10:09:02.594835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc1ca16e36f7'
down_revision = 'a93ea77efd2c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table("votes", 
    #                 sa.Column("user_id", sa.Integer(), nullable=False),
    #                 sa.Column("post_id", sa.Integer(), nullable=False),
    #                 sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete='CASCADE'),
    #                 sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete='CASCADE'),
    #                 sa.PrimaryKeyConstraint('user_id', 'post_id')
    # )
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table("votes")
    pass
    # ### end Alembic commands ###
